// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuryJWYxDDqkSyh8YUEXIGa0Obov264GA',
    appId: '1:487657765889:web:7c21cc4f17615fa9ec9400',
    messagingSenderId: '487657765889',
    projectId: 'real-time-flutter-2832f',
    authDomain: 'real-time-flutter-2832f.firebaseapp.com',
    storageBucket: 'real-time-flutter-2832f.firebasestorage.app',
    measurementId: 'G-KY78E3FTEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzS9ynK9UhEma6QaX0obvZotauj93oBSY',
    appId: '1:487657765889:android:34a3e7136632f83bec9400',
    messagingSenderId: '487657765889',
    projectId: 'real-time-flutter-2832f',
    storageBucket: 'real-time-flutter-2832f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp-X_pIuvt-q_sUIwhrNmDKX81Qw42cFI',
    appId: '1:487657765889:ios:0d1dc29b52507fdcec9400',
    messagingSenderId: '487657765889',
    projectId: 'real-time-flutter-2832f',
    storageBucket: 'real-time-flutter-2832f.firebasestorage.app',
    iosBundleId: 'com.example.templateBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp-X_pIuvt-q_sUIwhrNmDKX81Qw42cFI',
    appId: '1:487657765889:ios:0d1dc29b52507fdcec9400',
    messagingSenderId: '487657765889',
    projectId: 'real-time-flutter-2832f',
    storageBucket: 'real-time-flutter-2832f.firebasestorage.app',
    iosBundleId: 'com.example.templateBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuryJWYxDDqkSyh8YUEXIGa0Obov264GA',
    appId: '1:487657765889:web:15c3f442da743730ec9400',
    messagingSenderId: '487657765889',
    projectId: 'real-time-flutter-2832f',
    authDomain: 'real-time-flutter-2832f.firebaseapp.com',
    storageBucket: 'real-time-flutter-2832f.firebasestorage.app',
    measurementId: 'G-E69P0MPZFD',
  );
}
